site_name: shrinkr docs
site_description: Documentation for the shrinkr package
site_url: https://jgrzywaczewski.com/shrinkr/ # Update this later if using GitHub Pages
repo_url: https://github.com/ZetrextJG/shrinkr
repo_name: ZetrextJG/shrinkr

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZetrextJG
    - icon: fontawesome/solid/house
      link: https://jgrzywaczewski.com

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: numpy
            show_root_heading: true
            show_root_toc_entry: true
            filters:
              - "!^_"
              - "!^__all__$"
              - "!^__file__$"
              - "!^__name__$"
              - "!^__package__$"

nav:
  - Home: index.md
  - News: news.md
  - API Reference: api.md
